name: Publish

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

jobs:
  pypi:
    name: Upload to PyPI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install hatch
        run: pip install hatch
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install project
        run: pip install -e .
      - name: Build
        run: hatch build
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Install pdoc
        run: pip install pdoc~=13.0.0
      - name: Generate docs
        run:  pdoc --footer-text='Version ${{ github.ref_name }}' runj -o pdoc
      - name: Deploy docs (version)
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: pdoc
          clean: true
          clean-exclude: 'v*.*.*/'
          target-folder: "${{ github.ref_name }}"
      - name: Deploy docs (latest)
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: pdoc
          clean: false
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          body: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.ref_name }}"
